### ISSUE TITLE
[BUG] Nested view helpers need escaped quotes

### ISSUE THREAD

**Issue by cumuru** [stat1x/fluid-converter#8]
Reproduce: Enter
    
    <f:render partial="test_{f:translate(key:'test')}" />

and convert. Result is:

    {f:render(partial: 'test_{f:translate(key:'test')}')}

Expected result would read:

    {f:render(partial: 'test_{f:translate(key:\'test\')}')}

IIRC you need and odd number of backslashes to escape your single quotes, i.e. one backslash for first nested level, three for second, a.s.o. But I‘m not sure about this, needs to be checked.

**Comment by Scopestyle** [comment]
+1
